// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD88IU9v8sIGfOqfm0vsXvqFtIoSJLpH94',
    appId: '1:203710661305:web:c0b1a0c64e60b39ca45168',
    messagingSenderId: '203710661305',
    projectId: 'message-app-7bae8',
    authDomain: 'message-app-7bae8.firebaseapp.com',
    storageBucket: 'message-app-7bae8.firebasestorage.app',
    measurementId: 'G-ZLWXK4LSRV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB1AI1TzMaPnpqLWoiNwlseFxP2D4OZUo',
    appId: '1:203710661305:android:b1ae7b694c663422a45168',
    messagingSenderId: '203710661305',
    projectId: 'message-app-7bae8',
    storageBucket: 'message-app-7bae8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACkm8aD6kdrpOOSaL9RYnxqfmlsQ3icGA',
    appId: '1:203710661305:ios:04773bcebc14021ba45168',
    messagingSenderId: '203710661305',
    projectId: 'message-app-7bae8',
    storageBucket: 'message-app-7bae8.firebasestorage.app',
    iosClientId: '203710661305-h0dfs2nqr9a9jfij8lteh29qn87n6ajc.apps.googleusercontent.com',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACkm8aD6kdrpOOSaL9RYnxqfmlsQ3icGA',
    appId: '1:203710661305:ios:04773bcebc14021ba45168',
    messagingSenderId: '203710661305',
    projectId: 'message-app-7bae8',
    storageBucket: 'message-app-7bae8.firebasestorage.app',
    iosClientId: '203710661305-h0dfs2nqr9a9jfij8lteh29qn87n6ajc.apps.googleusercontent.com',
    iosBundleId: 'com.example.message',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD88IU9v8sIGfOqfm0vsXvqFtIoSJLpH94',
    appId: '1:203710661305:web:4a16fa7a5147bf97a45168',
    messagingSenderId: '203710661305',
    projectId: 'message-app-7bae8',
    authDomain: 'message-app-7bae8.firebaseapp.com',
    storageBucket: 'message-app-7bae8.firebasestorage.app',
    measurementId: 'G-L3P7FD3SQ6',
  );

}